version: '3.3'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somepassword
      MYSQL_DATABASE: servente
      MYSQL_USER: servente
      MYSQL_PASSWORD: servente
    ports:
      - "3306:3306"
volumes:
  db_data: {}
